name: canister
description: A versatile and extensible caching library written in pure Dart, offering Guava-like caching capabilities.
version: 1.0.0
repository: https://github.com/helightdev/canister

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
